name: flutter_application_4

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1
#flutter build apk

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^0.13.0
  http: ^0.13.6
  ffi: ^2.0.2
  universal_html: ^2.2.2
  image_picker: ^0.8.7+5
  geolocator: ^9.0.2
  path_provider: ^2.0.15
  connectivity: ^3.0.6
  # rename: ^2.1.1
  # flutter_http_proxy_widget: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/Logo_Dong_Nai.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

#add IMAGE
  assets: 
    - lib/assets/images/
